# Generated by Django 5.2.1 on 2026-02-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0023_dealcategory_discount_percent_traveldeal_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldeal',
            name='brochure',
            field=models.FileField(blank=True, help_text='Upload a PDF brochure for this travel deal', null=True, upload_to='deals/brochures/'),
        ),
    ]
